### PR TITLE
add {encode,decode}_async

### PR DESCRIPTION
**Pull request by yjh0502**
Add `xdelta3::encode_async`/`xdelta3::decode_async` which is an async streaming interface for xdelta3.

### CODE REVIEW

**Comment by yjh0502** [comment]
I added `lzma` feature flags to PR. `xdelta3` command uses lzma secondary compression by default when invoked with command-line interfaces. It means that almost all xdelta3-generated files cannot be decoded with the library is `lzma` is disabled.
`lzma` feature flag patch touches `Cargo.toml` and `Cargo.lock` which will cause tiresome merge conflict, so I appended the patch to this PR. Please feel free to let me know if you prefer separated PR for the feature.

**Comment by liushuyu** [comment]
> I added `lzma` feature flags to PR. `xdelta3` command uses lzma secondary compression by default when invoked with command-line interfaces. It means that almost all xdelta3-generated files cannot be decoded with the library is `lzma` is disabled.

I agree.

> `lzma` feature flag patch touches `Cargo.toml` and `Cargo.lock` which will cause tiresome merge conflict, so I appended the patch to this PR. Please feel free to let me know if you prefer separated PR for the feature.

I actually prefer to split `lzma` addition into a separate PR. There shouldn't be so many conflicts down the road.

**Comment by yjh0502** [comment]
@liushuyu got it, I removed last commit.

**Comment by liushuyu** [comment]
I think now you need to rebase your PR against the latest `master` branch.

Also, it would be nice to make `async` part optional since `async-std` is pretty large in size.
And I think this part can be its own separate module. For instance, `reqwest` contains a separate `async` module which contains all the `async` mode APIs.

Otherwise, this change is totally awesome to have!

**Comment by yjh0502** [comment]
@liushuyu I updated the PR, could you take a look at it?

**Review by liushuyu — APPROVED** [review]
Approved

**Pull request merged**
