### PR TITLE
use bindgen to generate bindings

### PR DESCRIPTION
**Pull request by yjh0502**

### CODE REVIEW

**Comment by liushuyu** [comment]
Hi! Thanks for your contribution!
Unfortunately, the tests are failing at the moment. Do you want to fix the tests yourself or do you want me to take care of it?

Thanks again

**Comment by yjh0502** [comment]
I'll try to fix the test, thanks for let me know!

**Comment by yjh0502** [comment]
@liushuyu I fixed the CI issue, thanks!

**Review by liushuyu — APPROVED** [review]
Looks good to me now!

Congratulations on the first Pull Request!

**Pull request merged**
